<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.example</groupId>
    <artifactId>application</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>database</artifactId>
  <packaging>jar</packaging>
  <properties>
    <flyway.version>11.9.1</flyway.version>
    <mariadb.client.version>3.5.3</mariadb.client.version>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-maven-plugin</artifactId>
        <version>${flyway.version}</version>
        <configuration>
          <url>${env.DB_URL}</url>
          <user>${env.DB_USERNAME}</user>
          <password>${env.DB_PASSWORD}</password>
          <locations>
            <location>filesystem:${project.basedir}/src/main/resources/db/migration</location>
          </locations>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
            <version>${flyway.version}</version>
          </dependency>
          <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>${mariadb.client.version}</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
</project>
